### ISSUE TITLE
Is possible to use with custom shape or aspect ratio?

### ISSUE THREAD

**Issue by michaldev** [icapps/flutter-custom-image-crop#10]
I would like to use this for crop my image for target size. For this use case I must define target size or aspect ratio (and manually resize it).

It support any from my requirements?

**Comment by vanlooverenkoen** [comment]
It is already posible to add a custom shape & aspect ratio. Not sure what you are looking for exactly.
This is not yet supported.
![image](https://user-images.githubusercontent.com/21172855/117109457-fb663580-ad84-11eb-9e76-983911fe2c32.png)

**Comment by demonskp** [comment]
Maybe you can give an example.
