### ISSUE TITLE
cropped image can't keep high quality

### ISSUE THREAD

**Issue by ZMNOTZ** [icapps/flutter-custom-image-crop#11]
I don’t know if you find that the picture after cropped is a jagged picture

**Comment by vanlooverenkoen** [comment]
Right now the picture will be the size of your canvas. This is something what we still need to fix.

**Comment by ZMNOTZ** [comment]
![image](https://user-images.githubusercontent.com/22322315/117532324-852e3100-b019-11eb-9708-295ce77f699f.png)
![image](https://user-images.githubusercontent.com/22322315/117532327-8b241200-b019-11eb-8a2a-cc64fe43249a.png)

Can you see the obvious change？

**Comment by vanlooverenkoen** [comment]
It is because at first the image is using its correct size. Then you resize it so it fits your shape. When clicking crop the canvas is used to get the new image instead of the original image.

**Comment by ZMNOTZ** [comment]
I set the size of the canvas when I created the canvas, but it didn’t work

**Comment by vanlooverenkoen** [comment]
The custom clipper is used on the canvas so that will result in the same problem

**Comment by ZMNOTZ** [comment]
It should be possible to use CustomClipper and RenderRepaintBoundary components. I used RenderRepaintBoundary to take screenshots. The image quality can be adjusted according to pixelRatio.

**Comment by vanlooverenkoen** [comment]
Yes that is possible, but that will still limit your max width & height to the max width & height of your canvas. If you are using an image of 2000x2000 and a device of 480x 640 your image will only have a max width & height of 480x640 (x pixel ratio)

**Comment by ikbendewilliam** [comment]
So there were two issues that caused this. One is that the image returned is depending on the screen size and the other one is filterQuality not set correctly. I've updated both and will create a PR asap.
This is the result:
![image](https://user-images.githubusercontent.com/20164321/145714304-25960f0e-6067-4a62-92d7-9b312d8dcc38.png)

**Comment by ikbendewilliam** [comment]
Versino 0.0.3 is available that fixes this issue
