### ISSUE TITLE
Disable rotating

### ISSUE THREAD

**Issue by guit4eva** [icapps/flutter-custom-image-crop#17]
Is it possible to disable rotating of an image?

**Comment by vanlooverenkoen** [comment]
What do you mean with `disable rotating of an image`? 
You can use the controller to rotate the image when you want.
Can you provide us with a minimal working example that we can copy and paste to find a solution for your issue?

**Comment by ikbendewilliam** [comment]
@Pisey-Nguon There is a PR open that adds this, #12 however there are still some issues that prevent us from merging and it seems that the creator of the PR isn't going to fix those. Feel free to fix them yourself or use their fork for now :-)

**Comment by vanlooverenkoen** [comment]
fixed by #23
