### ISSUE TITLE
how to do aspect ratio in this package?

### ISSUE THREAD

**Issue by DazzlingCVa** [icapps/flutter-custom-image-crop#19]
pls send me sample code

**Comment by ikbendewilliam** [comment]
There is currently no aspect ratio implemented, there is a PR which you can checkout and use https://github.com/demonskp/flutter-custom-image-crop but it's not ready to be merged so you'll have to use a git dependency

**Comment by Joseph-Nathan** [comment]
any news !

**Comment by ikbendewilliam** [comment]
As far as I can tell, no work has been done on the PR. Feel free to take a look! I'm working on some other packages atm as this is not priority for us. But if you (or someone) fixes the PR, we'd be happy to take a look and merge 🙂
