### ISSUE TITLE
Initial scaling

### ISSUE THREAD

**Issue by sante** [icapps/flutter-custom-image-crop#21]
Is there a way to provide initial scaling? Or set the image to cover all the space it has?

**Comment by ikbendewilliam** [comment]
You can scale programmatically with the controller.
```dart
controller.addTransition(CropImageData(scale: 0.75)));
```
There is currently no way to cover all the space it has in the package, you will have to do the calculation and scale. Or feel free to add this option in a PR :-).

**Comment by vlkonoshenko** [comment]
Looks like now plugin have imageFit params. So issue can be close
