### ISSUE TITLE
why crop result always is square

### ISSUE THREAD

**Issue by SG-XM** [icapps/flutter-custom-image-crop#39]
<img width="399" alt="image" src="https://github.com/icapps/flutter-custom-image-crop/assets/32589854/e4d62760-b558-4f1e-978f-38c8d88f9d28">

<img width="399" alt="image" src="https://github.com/icapps/flutter-custom-image-crop/assets/32589854/aa80d039-f806-4fba-8644-6945aa9fa64a">

**Comment by SG-XM** [comment]
and this is resultpage, I wrap the image with contianer, and set color yellow
```
     body: Center(
        child: Column(
          children: [
            const Spacer(),
            Container(color:Colors.yellow,child:
            Image(
              image: image,
            ),),
            ElevatedButton(
              child: const Text('Back'),
              onPressed: () => Navigator.of(context).pop(),
            ),
            const Spacer(),
          ],
```

**Comment by SG-XM** [comment]
> Did you change anything about the example project?

even if i download this repo without any modification of code,the result also is square

**Comment by ikbendewilliam** [comment]
What is your question exactly? The result is always a square since images are always squares. We can crop the image, but eventually it will result in a square. For now the background color is white, you can change that by setting the `backgroundColor`. 
The issue is that you can't simply crop a widget for now. What I do is draw it on a canvas and convert that canvas to an image. A canvas can't be transparant, so you always have a background color. What you could do is convert the pixels afterwards, but this requires some additional code. Feel free to open a PR for this!

**Comment by SG-XM** [comment]
> What is your question exactly? The result is always a square since images are always squares. We can crop the image, but eventually it will result in a square. For now the background color is white, you can change that by setting the `backgroundColor`. The issue is that you can't simply crop an image for now. What we do is draw it on a canvas and convert that canvas to an image. A canvas can't be transparant, so you always have a background color. What you could do is convert the pixels afterwards, but this requires some additional code. Feel free to open a PR for this!

Thanks for your explanation, I misunderstood the function of this repo. I had assumed  that the canvas would be created with the same size of croparea rather than the size of originimage.

**Comment by ikbendewilliam** [comment]
The reason we use the original size is that different devices should have the same result. Otherwise, if you crop on a small phone, the resulting image is pixelated even if you use a high res image. You can resize the result if you'd like.

**Comment by SG-XM** [comment]
> Thanks for your explanation

Thanks for your explanation

> The reason we use the original size is that different devices should have the same result. Otherwise, if you crop on a small phone, the resulting image is pixelated even if you use a high res image. You can resize the result if you'd like.

Thanks for your explanation, I will close this issue.
