### ISSUE TITLE
Have background white after crop to circle

### ISSUE THREAD

**Issue by MrHafid** [icapps/flutter-custom-image-crop#47]
![Screenshot 2023-09-30 at 00 09 37](https://github.com/icapps/flutter-custom-image-crop/assets/43329305/4b1c9449-e18f-4383-8b0c-94779d279f60)
background white in crop circle, but I dont know this bug or me not knw for this setting .

**Comment by ikbendewilliam** [comment]
You can choose your background color in the widget. Unfortunately due to limitations in the canvas API you can't have a transparant background. If this is what you are expecting
