### ISSUE TITLE
Landscape crop area shape and portrait images - initial fit by height 

### ISSUE THREAD

**Issue by JustUserHere** [icapps/flutter-custom-image-crop#50]
Hello dear,
with forceInsideCropArea: true  portrait images on init fits by height and not by width. If zoom in/out button pressed it is zoomed to fit width (as it should be). I found workaround how to solve it, but probably it can be implemented in initial logic. 
// Delay and then zoom in the image to fit the width
    Future.delayed(Duration(milliseconds: 100), () {
      _croppController.addTransition(CropImageData(scale: 1.00001));

thanks!

**Comment by ikbendewilliam** [comment]
It took a while to reproduce, but it has to do with setting imageFit for example to fitCropHeight and providing a portrait image. Meaning that the initial values are out of bounds. I'm looking into it to see if we can fix this

**Comment by ikbendewilliam** [comment]
I managed to get this working. I just released 0.1.1 with this fix.
