### ISSUE TITLE
Crop bug if Ratio width < height

### ISSUE THREAD

**Issue by Z6P0** [icapps/flutter-custom-image-crop#52]
I tested with `ratio: Ratio(width: 2, height: 3)` and the cropped image does not match.
It works with square and width > height.

**Comment by RockyPanchal** [comment]
Hello, I faced the same issue earlier, I understand the core code and made changes in one of the file in library. then its works fine

Please do changes in that file and check 
- in calculate_on_crop_params.dart file 
-caclulateOnCropParams function 

replace below code at the end , It will definitely works,

I made changes in cropSizeHeight, cropSizeWidth parameter  according to aspect ratio


final double cropSizeWidth;
  final double cropSizeHeight;
  if (aspectRatio > 1) {
    cropSizeWidth = cropSizeMax;
    cropSizeHeight = cropSizeWidth / aspectRatio;
  } else {
    cropSizeHeight = cropSizeMax / aspectRatio;
    cropSizeWidth = cropSizeHeight * aspectRatio;
  }
  return OnCropParams(
    cropSizeHeight: cropSizeHeight,
    cropSizeWidth: cropSizeWidth,
    translateScale: translateScale,
    scale: scale,
  );
  
  Thanks

**Comment by TarasBounty** [comment]
Also face the same issue
@ikbendewilliam please take a look

**Comment by RockyPanchal** [comment]
@TarasBounty , Please check my answer, It will help you as i faced it and solve

**Comment by TarasBounty** [comment]
@RockyPanchal Thanks, I saw it. Hope @ikbendewilliam will fix it in the next package release and we can use it without a "fork workaround"

**Comment by ikbendewilliam** [comment]
Currently we are very busy with projects, if you have a fork with a fix, please create a PR so we can have this fix available for everyone :-)

**Comment by TarasBounty** [comment]
> Currently we are very busy with projects, if you have a fork with a fix, please create a PR so we can have this fix available for everyone :-)

@RockyPanchal

**Comment by ikbendewilliam** [comment]
Fixes have been merged and published in v0.1.0
