### ISSUE TITLE
Overlay color affects the Image

### ISSUE THREAD

**Issue by Govindbetterlives** [icapps/flutter-custom-image-crop#54]
Hi,

I use this package. I select the image and display the image in the ShowDialog. However, the image is affected by overlay color.

Version: custom_image_crop: ^0.0.13

We rendering "**Flutter run -d chrome --web-renderer html**".

For your reference
![image](https://github.com/icapps/flutter-custom-image-crop/assets/81243940/5549f9be-8c41-4af6-b3af-9174bb6cd79b)

**Comment by ikbendewilliam** [comment]
I think `--web-renderer html` can cause issues, do you also have it with canvaskit? 
Do you also have it if you run the example project? It might also be related to the dialog 🤔
